CREATE TABLE ActivityLogs (
  LogId INT NOT NULL AUTO_INCREMENT,
  Action VARCHAR(255) NOT NULL,
  EntityName VARCHAR(100) NOT NULL,
  EntityId INT NOT NULL,
  Details TEXT,
  Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UserName VARCHAR(100) NOT NULL,
  PRIMARY KEY (LogId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
